### ISSUE TITLE
Web server is being blocked by the new LDR code

### ISSUE THREAD

**Issue by chunkysteveo** [witnessmenow/arduino-alarm-clock#2]
Hey Brian. Although the LDR code works great. Was just testing getting to the webserver of the ESP and it keeps timing out. Reverting back to the code prior to May 4th and the code works fine - Alarm Set page comes up.

Looking into this now for you.

Steve

**Comment by chunkysteveo** [comment]
Found it, line 327 adjustBrightness(); needs to be removed.

**Comment by witnessmenow** [comment]
Pushed the change there, thanks @chunkysteveo !
